# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e5ff60da9811cc562ef08e26adb354a1a5a5314de9639f656113ce77b03064f338dc716169a66ead4e0d38b61b7aefb554925683edcdf637e1bf0180d5e87567

test:
  secret_key_base: a90b160cb852b23738274d693e818a779962acb6d6ac6e62f05379b67754a68ab25bef7f19929a1cba61f5d5ccea44574762177c8dde582e2418621260edd1a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
